name: schemake
description: Schemake (schema make) is a library for generating Dart code and schemas from a programmatic schema specification.
version: 0.1.0
repository: https://github.com/renatoathaydes/schemake

environment:
  sdk: ^3.1.1

dependencies:
  collection: ^1.18.0
  conveniently: ^1.2.0

dev_dependencies:
  yaml: ^3.1.2
  lints: ^2.0.0
  test: ^1.21.0
  dartle: ^0.26.0
  path: ^1.8.3
