name: schemake
description: >
  Schemake (schema make) is a package for describing schemas from a declarative specification.
  Specifications can then be used for validating data, generating code or other schemas like JSON Schema and more.
version: 0.1.0
repository: https://github.com/renatoathaydes/schemake

environment:
  sdk: ^3.1.1

dependencies:
  collection: ^1.18.0
  conveniently: ^1.2.0
  dart_casing: ^3.0.1

dev_dependencies:
  yaml: ^3.1.2
  lints: ^2.0.0
  test: ^1.21.0
  dartle: ^0.26.0
  path: ^1.8.3
